---
title: UME
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: christieha@gmail.com
description: We are UME. We are a design firm. We use design to create balance in
  the world by connecting mission-driven companies, women and girls through branding,
  workshops and philanthropy.
baseurl: 
url: http://ume.design
twitter_username: 
github_username: christieha
markdown: kramdown
