---
title: Christie Ha | Art Director and Designer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: christieha@gmail.com
description: Hello
baseurl: 
url: christieha.com
twitter_username: 
github_username: christieha
markdown: kramdown
